### ISSUE TITLE
希望支持tokudb_dir_per_db参数

### ISSUE THREAD

**Issue by GHMIAO** [alibaba/AliSQLBackup#1]
另外不支持tokudb_data_dir指定其他路径

**Comment by fungo** [comment]
@GHMIAO 

非常感谢您的建议。

现在 AliSQL 还不支持 `tokudb_dir_per_db` 这个参数，所以备份工具还没支持。后面AliSQL支持这个参数后，备份工具会相应改进。

`tokudb_data_dir`是支持的，限制条件是要求这个目录在 `datadir` 下面。

**Comment by GHMIAO** [comment]
感谢回复与分享
